name: just a simple demo for cli action
on:
  workflow_dispatch:
    inputs:
      secret_name:
        type: choice
        required: true
        description: 'secert key that contians the json'
        options:
          - eaas_params
      json_key:
        type: choice
        required: true
        description: 'key to parse from the secret json'
        options:
          - aws
          - azure
      my_env:
        type: environment
        required: true
        
jobs:
  test_job:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.my_env }}
    steps:
      - name: Run some command
        id: get_secert_step
        uses: cloudify-cosmo/cli-action@v1.2
        with:
          command: "secrets get --json ${{ github.event.inputs.secret_name }}" 

      - name: Parse Secret value
        shell: python
        run: |
          import os
          import json
          import pprint
          env_var = os.environ
          print("User's Environment variable:")
          pprint.pprint(dict(env_var), width = 1)
          cli_output = ${{steps.get_secert_step.outputs.cli-output}}
          json_val = json.loads(json.loads(cli_output)['value'])['${{ github.event.inputs.json_key }}']
          print('json_val {0}'.format(json_val))

          
env:
  CLOUDIFY_HOST: ${{ secrets.CLOUDIFY_HOST }}
  CLOUDIFY_USERNAME: ${{ secrets.CLOUDIFY_USERNAME }}
  CLOUDIFY_PASSWORD: ${{ secrets.CLOUDIFY_PASSWORD }}
  CLOUDIFY_TENANT: ${{ secrets.CLOUDIFY_TENANT }}
  CLOUDIFY_SSL: ${{ secrets.CLOUDIFY_SSL }}
