name: just a simple demo for cli action
on:
  workflow_dispatch:
    inputs:
      env_type:
        required: true
        description: 'json main key value'  
jobs:
  test_job:
    runs-on: ubuntu-latest
    environment: manager-oversight
    steps:
      - name: Run some command
        uses: cloudify-cosmo/cli-action@v1.2
        with:
          command: "secerts get ${{ github.event.inputs.env_type }}" 
          set-output: false
          
env:
  CLOUDIFY_HOST: ${{ secrets.CLOUDIFY_HOST }}
  CLOUDIFY_USERNAME: ${{ secrets.CLOUDIFY_USERNAME }}
  CLOUDIFY_PASSWORD: ${{ secrets.CLOUDIFY_PASSWORD }}
  CLOUDIFY_TENANT: ${{ secrets.CLOUDIFY_TENANT }}
  CLOUDIFY_SSL: ${{ secrets.CLOUDIFY_SSL }}
