name: just a simple demo for cli action
on:
  workflow_dispatch:
    inputs:
      secret_name:
        required: true
        description: 'secert key that contians the json'  
      json_key:
         required: true
         description: 'key to parse from the secret json'       
jobs:
  test_job:
    runs-on: ubuntu-latest
    environment: manager-oversight
    steps:
      - name: Run some command
        id: get_secert_step
        uses: cloudify-cosmo/cli-action@v1.2
        with:
          command: "secrets get --json ${{ github.event.inputs.secret_name }}" 
          set-output: true
      - name: Parse Secret value
        shell: bash
        run: |
          sudo apt-get install jq -y
          key_val=`${{steps.get_secert_step.outputs.cli-output}} | jq -r '.value.${{ github.event.inputs.json_key }}'`
          echo "$key_val"
          
env:
  CLOUDIFY_HOST: ${{ secrets.CLOUDIFY_HOST }}
  CLOUDIFY_USERNAME: ${{ secrets.CLOUDIFY_USERNAME }}
  CLOUDIFY_PASSWORD: ${{ secrets.CLOUDIFY_PASSWORD }}
  CLOUDIFY_TENANT: ${{ secrets.CLOUDIFY_TENANT }}
  CLOUDIFY_SSL: ${{ secrets.CLOUDIFY_SSL }}
