name: just a simple demo for cli action
on:
  workflow_dispatch:
    inputs:
      secret_name:
        required: true
        description: 'secert key that contians the json'  
      json_key:
         required: true
         description: 'key to parse from the secret json'       
jobs:
  test_job:
    runs-on: ubuntu-latest
    environment: manager-oversight
    steps:
      - name: Run some command
        id: get_secert_step
        uses: cloudify-cosmo/cli-action@v1.2
        with:
          command: "secrets get --json ${{ github.event.inputs.secret_name }}" 

      - name: Parse Secret value
        shell: python
        run: |
          import json
          cli_output = ${{steps.get_secert_step.outputs.cli-output}}
          pretty_cost = json.loads(cli_output)['value']['${{ github.event.inputs.json_key }}']
          print('pretty_cost {0}'.format(pretty_cost))
          pretty_cost = pretty_cost.replace('%','%25')
          pretty_cost = pretty_cost.replace('\n','%0A')
          pretty_cost = pretty_cost.replace('\r','%0D')
          print ('::set-output name=cost::{0}'.format(pretty_cost))
          
env:
  CLOUDIFY_HOST: ${{ secrets.CLOUDIFY_HOST }}
  CLOUDIFY_USERNAME: ${{ secrets.CLOUDIFY_USERNAME }}
  CLOUDIFY_PASSWORD: ${{ secrets.CLOUDIFY_PASSWORD }}
  CLOUDIFY_TENANT: ${{ secrets.CLOUDIFY_TENANT }}
  CLOUDIFY_SSL: ${{ secrets.CLOUDIFY_SSL }}
